import { Poppins , Vazirmatn} from "next/font/google";
import "./globals.css";


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["200","300","400","500","600","700","800","900"]
});

const vazirMatn = Vazirmatn({
  variable: "--font-vazir",
  subsets: ["arabic"],
  weight: ["200","300","400","500","600","700","800","900"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${vazirMatn.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
